### ISSUE TITLE
[PS-16-DZ] Kingart dimmer does not respond after uploading with ESPHome 2022.3.2

### ISSUE THREAD

**Issue by denisfrench** [alryaz/esphome-components#2]
Hi; your PS-16-DZ external component might need updating for use with recent versions of ESPhome.

I've tried the example.yaml with only wifi credentals changed. It appears to compile and upload without error, however the Kingart dimmer does not seem to respond to API calls. esphome-dashboard cannot connect to the device log, and Home Assistant does not prompt to add the device. The device's webpage does not load.

Luckily esphome-dashboard can still push an OTA update, so I was able to recover using a minimal setup, and then use the device's webpage to reload Tasmota.

The esphome issue tracker indicates a few external components have broken recently with the release of 2022.3, possibly related to this PR; https://github.com/esphome/esphome/pull/3216

The Python/C++ code within external components is well beyond my understanding; I would appreciate it if you could take a look.

Best regards,
Denis.

**Comment by alryaz** [comment]
Will do, thanks for the heads up!

**Comment by denisfrench** [comment]
I have got this successfully working by downgrading esphome to v2022.1.4 .

Later versions of esphome do not work, i.e. 2022.2.0b1 introduces a breaking change.

Best regards,
Denis.

**Comment by alryaz** [comment]
Hello, @denisfrench !
I am sorry for getting back to you as late as it can ever get.
Unfortunately, certain life scenarios prevent me from working on the component further.
I have attempted (with plentiful success) to update my code to work with the latest ESPHome (as I have suffered a similar issue). In addition, it should fix jumpy lights whenever light is turned on back from sleep.

**Comment by denisfrench** [comment]
Confirmed working well at my end.

Thanks for your work on this, and for sharing with the community.

Conversion of all my esp8266 devices from Tasmota to ESPHome is now complete 😃
